name: Update Formula on Release

on:
  repository_dispatch:
    types: [clitris_release]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download new tarball
        run: |
          wget ${{ github.event.client_payload.tarball_url }} -O clitris.tar.gz

      - name: Calculate SHA256
        id: sha
        run: echo "sha256=$(shasum -a 256 clitris.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          sed -i "s|url \".*\"|url \"${{ github.event.client_payload.tarball_url }}\"|" Formula/clitris.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha256 }}\"|" Formula/clitris.rb

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/clitris.rb
          git commit -m "Update clitris formula for ${{ github.event.client_payload.version }}"
          echo "Pushing changes to GitHub..."
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/FinityFly/homebrew-tap.git
          echo "Pushing changes to main branch..."
          git push origin main